version: 1
accounts:
- name: kii1
  coins: [ 300000000000000ukii ]
- name: kii2
  coins: [ 100000000000000ukii ]
- name: kii3
  coins: [ 100000000000000ukii ]
faucet:
  name: kii1
  coins: [ 100000000000000ukii ]
genesis:
  chain_id: kiiventador
  app_state:
    staking:
      params:
        bond_denom: ukii
validators:
- name: kii1
  bonded: 100000000000ukii
  app:
    pruning: "nothing"
  config:
    moniker: "kiiventador-1"
  client:
    output: "json"
