version: 1
accounts:
- name: alice
  coins: [ 200000000000ukii ]
- name: bob
  coins: [ 200000000000ukii ]
- name: test
  coins: [ 200000000000ukii ]
faucet:
  name: bob
  coins: [ 200000000000ukii ]
client:
  typescript:
    path: ts-client
  hooks:
    path: kii-web/src/hooks
  openapi:
    path: docs/static/openapi.yml
genesis:
  app_state:
    staking:
      params:
        bond_denom: ukii
validators:
- name: test
  bonded: 100000000000ukii
