version: 1
accounts:
- name: kii1
  coins: [ 200000000000ukii ]
  mnemonic: shine pledge alert isolate together fee hurry canal admit athlete cotton another fiction caught dutch system world pear candy street dream sudden reflect embark 
- name: kii2
  coins: [ 200000000000ukii ]
  mnemonic: thrive energy lumber bar midnight fee someone frame code jelly cram belt palm sail shy among help inspire deny suffer mercy struggle more return     
- name: kii3
  coins: [ 200000000000ukii ]
  mnemonic: print rigid weekend mixture web try alley usual swamp boy tree define obvious excite sponsor sheriff cave find nut woman garment few crowd cram
faucet:
  name: kii1
  coins: [ 200000000000ukii ]
genesis:
  app_state:
    staking:
      params:
        bond_denom: ukii
validators:
- name: kii1
  bonded: 100000000000ukii
  home: "~/.kiichain"
  app:
    pruning: "nothing"
  config:
    moniker: "kiiventador-1"
  client:
    output: "json"
