version: 1
accounts:
- name: private_sale
  coins: [ 54000000000000tkii ]
- name: public_sale
  coins: [ 126000000000000tkii ]
- name: liquidity
  coins: [ 180000000000000tkii ]
- name: community_development
  coins: [ 180000000000000tkii ]
- name: team
  coins: [ 356000000000000tkii ]
- name: rewards
  coins: [ 900000000000000tkii ]
- name: kiiventadorwallet
  coins: [ 1000000000000tkii ]
- name: kiiferrari458wallet
  coins: [ 1000000000000tkii ]
- name: kiiuruswallet
  coins: [ 1000000000000tkii ]
- name: kiipaganiwallet
  coins: [ 1000000000000tkii ]
genesis:
  chain_id: kiiventador
  app_state:
    crisis:
      constant_fee:
        denom: tkii
    mint:
      minter:
        inflation: "0.0"
      params:
        inflation_max: "0.0"
        inflation_min: "0.0"
        inflation_rate_change: "0.0"
        mint_denom: tkii
    staking:
      params:
        bond_denom: tkii
validators:
- name: kiiventadorwallet
  bonded: 100000000000tkii
  app:
    pruning: "default"
  config:
    moniker: "KiiAventador"
  client:
    output: "json"
